ifd3f/caligula

.github/workflows/ci-unix.yml
.github/workflows/ci.yml
.gitignore
flake.nix
nix/cross-helpers.nix
nix/default.nix

Does it build? Yep!
Does it actually run? ¯\\\_(ツ)\_/¯

Add aarch64-linux cross compilation to CI

---

flake.nix
nix/cross-helpers.nix

Closes #23 
Turns out you just need to override `CC_aarch64_unknown_linux_musl`

Fix cross-compiling C to aarch64-linux

---

Cargo.lock
Cargo.toml
src/hash.rs
src/main.rs
src/ui/ask_hash.rs
src/ui/ask_outfile.rs
src/ui/cli.rs
src/ui/main.rs
src/ui/mod.rs

Implement hash verification

---

Cargo.lock
Cargo.toml
README.md
src/ui/cli.rs

The branch name is unrelated to the sketchy therapy company.

Improve the CLI help message

---

src/compression.rs
src/ui/ask_outfile.rs
src/ui/cli.rs

Differentiate `--compression ask` and `--compression auto` flags

---

nix/cross-helpers.nix

This prevents annoying cache misses in the Nix build when editing non-Rust source files.

Hide extraneous source files in rust build

---

.github/workflows/ci.yml

This fixes the "system integrity protection" bug.

Bump CI action versions

---

.github/workflows/ci-unix.yml

fucking hate github actions fr

Bump version in ci-unix

---

src/ui/ask_hash.rs

Make it more clear that you can skip.

Improve "ask hash" message

---

Cargo.lock
Cargo.toml

Where'd v0.4.1 go?
my dumbass forgot to update the cargo.toml...

Bump to release v0.4.2

---

build.rs
native/darwin/enumdisk.h
native/darwin/enumdisk.m

We don't use any objc++ features anyways.

Make enumdisk objc instead of objc++

---

Cargo.lock
Cargo.toml
src/ui/burn/fancy/display.rs
src/ui/burn/fancy/widgets.rs
src/ui/utils.rs

it's deprecated and ratatui is the replacement nyaaa

Replace tui with ratatui

---

Cargo.lock
Cargo.toml

Bump version for v0.4.3

---

Cargo.lock
Cargo.toml
src/burn/child.rs
src/burn/state_tracking.rs
src/logging.rs
src/ui/ask_hash.rs
src/ui/ask_outfile.rs
src/ui/burn/fancy/display.rs
src/ui/burn/fancy/state.rs
src/ui/burn/start.rs

I don't know if this will ever be useful but hey, better logged than unlogged!

Throw logging and spans everywhere

---

src/byteseries.rs
src/ui/burn/fancy/display.rs
src/ui/burn/fancy/state.rs
src/ui/burn/fancy/widgets.rs

This makes the code much clearer and makes the widgets more self-contained.

Refactor TUI components to implement Widget trait

---

Cargo.lock
Cargo.toml
src/ipc_common.rs
src/main.rs
src/writer_process/child.rs
src/writer_process/handle.rs
src/writer_process/ipc.rs

Needed as part of multi-disk UI efforts (#64). 
This reverts #61.

Bring named sockets back

---

README.md

yes, i know, i'm chickening out here but not everyone is perfect!

Relax the size SLA

---

.github/workflows/ci.yml
Cargo.lock
flake.lock

updates only, no upgrades. upgrades go in another pr

2024-05-03 updates

---

.github/workflows/ci-unix.yml
.github/workflows/ci.yml
.github/workflows/publish.yml
flake.nix

also fix a little Oopsie! i had in the lint script. i guess the shebang isn't there anymore

Update the github actions

---

Cargo.lock
Cargo.toml

Bump version to v0.4.4

---

Cargo.toml
src/compression.rs
src/ui/simple_ui/ask_hash.rs
src/ui/simple_ui/ask_outfile.rs
src/writer_process/child.rs

This seems extra and unnecessary.

Remove feature flags for disabling specific compression algorithms

---

src/ui/fancy_ui/display.rs
src/ui/fancy_ui/state.rs
src/ui/fancy_ui/widgets.rs

Brought up in #107.
Adds a more informative quit dialog.

Add confirmation prompt for closing

---

Cargo.lock
Cargo.toml
src/compression.rs
src/compression/zstd_streaming_decoder.rs

I would like to publish 0.4.7 soon and this being a git dependency thing is probably the last thing blocking the release. Since it's just this one struct, we'll just work around it for the time being :)

Temporary workaround for the zstd-rs PR not being merged yet

---

Cargo.lock
Cargo.toml

Bump version to v0.4.7

---

README.md

Update README.md with cargo install instructions

---

Cargo.lock

chore: update Cargo.lock for the new version
